### ISSUE TITLE
notes on final scores

### ISSUE THREAD

**Issue by jlgeist** [sethatwood/poly-n-back#3]
A couple notes on final scores:

- Make high score resettable
- At the conclusion of the game, bigger presentation of final score plus accuracy percentage

**Comment by sethatwood** [comment]
![Screen Shot 2023-11-21 at 8 21 58 PM](https://github.com/sethatwood/poly-n-back/assets/35325251/b8bcd7e3-f12c-4ff8-9a1c-254314801591)

@jlgeist here's a screenshot of the improved final score screen. what do you think?

could you please confirm everything is accurate on https://polynback.fun ? thanks!

( I'll tackle the resettable high score next )
